export const blogsData = [
  {
    id: 1,
    title: "html",
    body: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Id facilis asperiores quidem corrupti corporis distinctio excepturi dolores hic nostrum ea laboriosam, error, temporibus blanditiis rem sunt expedita. Nihil officia veritatis obcaecati laudantium quo sint nam placeat doloremque dolor quis iure velit praesentium neque inventore quae, culpa eos vero, labore possimus! Neque reiciendis dolorem similique dolorum aut itaque aliquid explicabo odio necessitatibus voluptates expedita id, quidem, illo harum ducimus veniam. Sed consequatur deleniti ipsum animi eligendi dolorem eveniet laudantium voluptatibus molestiae veritatis est, nemo voluptatem nihil at sunt. Dolor sed earum veniam nostrum perferendis. Voluptatem illum beatae commodi cumque nostrum sunt vero numquam aut autem, quis officia quidem sit iure laborum ipsam tempore quae totam. Voluptatum, ad delectus eveniet, culpa ab necessitatibus sapiente, fugit recusandae dolore impedit asperiores fuga deserunt laborum. Dolores enim autem doloribus tenetur nemo id nisi sequi! Qui, sapiente, dolorum optio enim porro ratione voluptates recusandae quas ex repellat quo veritatis modi rem atque dolorem ullam amet laborum quis. Distinctio, ipsum eveniet accusamus omnis sint obcaecati. At, impedit?",
  },
  {
    id: 2,
    title: "css",
    body: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Id facilis asperiores quidem corrupti corporis distinctio excepturi dolores hic nostrum ea laboriosam, error, temporibus blanditiis rem sunt expedita. Nihil officia veritatis obcaecati laudantium quo sint nam placeat doloremque dolor quis iure velit praesentium neque inventore quae, culpa eos vero, labore possimus! Neque reiciendis dolorem similique dolorum aut itaque aliquid explicabo odio necessitatibus voluptates expedita id, quidem, illo harum ducimus veniam. Sed consequatur deleniti ipsum animi eligendi dolorem eveniet laudantium voluptatibus molestiae veritatis est, nemo voluptatem nihil at sunt. Dolor sed earum veniam nostrum perferendis. Voluptatem illum beatae commodi cumque nostrum sunt vero numquam aut autem, quis officia quidem sit iure laborum ipsam tempore quae totam. Voluptatum, ad delectus eveniet, culpa ab necessitatibus sapiente, fugit recusandae dolore impedit asperiores fuga deserunt laborum. Dolores enim autem doloribus tenetur nemo id nisi sequi! Qui, sapiente, dolorum optio enim porro ratione voluptates recusandae quas ex repellat quo veritatis modi rem atque dolorem ullam amet laborum quis. Distinctio, ipsum eveniet accusamus omnis sint obcaecati. At, impedit?",
  },
  {
    id: 3,
    title: "js",
    body: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Id facilis asperiores quidem corrupti corporis distinctio excepturi dolores hic nostrum ea laboriosam, error, temporibus blanditiis rem sunt expedita. Nihil officia veritatis obcaecati laudantium quo sint nam placeat doloremque dolor quis iure velit praesentium neque inventore quae, culpa eos vero, labore possimus! Neque reiciendis dolorem similique dolorum aut itaque aliquid explicabo odio necessitatibus voluptates expedita id, quidem, illo harum ducimus veniam. Sed consequatur deleniti ipsum animi eligendi dolorem eveniet laudantium voluptatibus molestiae veritatis est, nemo voluptatem nihil at sunt. Dolor sed earum veniam nostrum perferendis. Voluptatem illum beatae commodi cumque nostrum sunt vero numquam aut autem, quis officia quidem sit iure laborum ipsam tempore quae totam. Voluptatum, ad delectus eveniet, culpa ab necessitatibus sapiente, fugit recusandae dolore impedit asperiores fuga deserunt laborum. Dolores enim autem doloribus tenetur nemo id nisi sequi! Qui, sapiente, dolorum optio enim porro ratione voluptates recusandae quas ex repellat quo veritatis modi rem atque dolorem ullam amet laborum quis. Distinctio, ipsum eveniet accusamus omnis sint obcaecati. At, impedit?",
  },
  {
    id: 4,
    title: "react",
    body: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Id facilis asperiores quidem corrupti corporis distinctio excepturi dolores hic nostrum ea laboriosam, error, temporibus blanditiis rem sunt expedita. Nihil officia veritatis obcaecati laudantium quo sint nam placeat doloremque dolor quis iure velit praesentium neque inventore quae, culpa eos vero, labore possimus! Neque reiciendis dolorem similique dolorum aut itaque aliquid explicabo odio necessitatibus voluptates expedita id, quidem, illo harum ducimus veniam. Sed consequatur deleniti ipsum animi eligendi dolorem eveniet laudantium voluptatibus molestiae veritatis est, nemo voluptatem nihil at sunt. Dolor sed earum veniam nostrum perferendis. Voluptatem illum beatae commodi cumque nostrum sunt vero numquam aut autem, quis officia quidem sit iure laborum ipsam tempore quae totam. Voluptatum, ad delectus eveniet, culpa ab necessitatibus sapiente, fugit recusandae dolore impedit asperiores fuga deserunt laborum. Dolores enim autem doloribus tenetur nemo id nisi sequi! Qui, sapiente, dolorum optio enim porro ratione voluptates recusandae quas ex repellat quo veritatis modi rem atque dolorem ullam amet laborum quis. Distinctio, ipsum eveniet accusamus omnis sint obcaecati. At, impedit?",
  },
  {
    id: 5,
    title: "node",
    body: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Id facilis asperiores quidem corrupti corporis distinctio excepturi dolores hic nostrum ea laboriosam, error, temporibus blanditiis rem sunt expedita. Nihil officia veritatis obcaecati laudantium quo sint nam placeat doloremque dolor quis iure velit praesentium neque inventore quae, culpa eos vero, labore possimus! Neque reiciendis dolorem similique dolorum aut itaque aliquid explicabo odio necessitatibus voluptates expedita id, quidem, illo harum ducimus veniam. Sed consequatur deleniti ipsum animi eligendi dolorem eveniet laudantium voluptatibus molestiae veritatis est, nemo voluptatem nihil at sunt. Dolor sed earum veniam nostrum perferendis. Voluptatem illum beatae commodi cumque nostrum sunt vero numquam aut autem, quis officia quidem sit iure laborum ipsam tempore quae totam. Voluptatum, ad delectus eveniet, culpa ab necessitatibus sapiente, fugit recusandae dolore impedit asperiores fuga deserunt laborum. Dolores enim autem doloribus tenetur nemo id nisi sequi! Qui, sapiente, dolorum optio enim porro ratione voluptates recusandae quas ex repellat quo veritatis modi rem atque dolorem ullam amet laborum quis. Distinctio, ipsum eveniet accusamus omnis sint obcaecati. At, impedit?",
  },
];
